Repository IATI/pyIATI, pull requests merged in 2018-08, with the labels that each got.

#312 Add validation to readme
  README.md
Labels: docs, enhancement, incomplete

#318 Update docs gen
  .gitignore
  .travis.yml
  Makefile
  README.md
  docs/source/index.rst
Labels: complete, docs, enhancement

#319 Fix typos and sentences that do not read correctly, delete comments n…
  README.md
  RELEASING.md
  iati/resources.py
  iati/tests/resources.py
  iati/tests/test_version.py
  iati/validator.py
  iati/version.py
Labels: complete, docs, enhancement

#320 Update docs gen, update README
  README.md
  iati/data.py
  iati/version.py
Labels: bug-fixes, complete, docs, enhancement
