Repository IATI/pyIATI, pull requests merged in 2018-02, with the labels that each got.

#275 [requires.io] dependency update on dev branch
  requirements-dev.txt
Labels: complete, repo-management

#274 Make changes for 0.3.0 bump
  CHANGELOG.md
  docs/source/conf.py
  setup.cfg
  setup.py
Labels: complete, repo-management

#278 Run travis tests in parallel
  .travis.yml
Labels: complete, repo-management, tests

#279 Add decorators to restrict versions passed to functions
  CHANGELOG.md
  iati/constants.py
  iati/default.py
  iati/resources.py
  iati/tests/conftest.py
  iati/tests/test_constants.py
  iati/tests/test_default.py
  iati/tests/test_resources.py
  iati/tests/test_version.py
  iati/utilities.py
  iati/version.py
Labels: code-features, complete, enhancement
